// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD87lsqTNGwvcecyoitYoBJ6QZCKoyCRQ',
    appId: '1:1392979323:web:815bca20da2b96314461de',
    messagingSenderId: '1392979323',
    projectId: 'ccms-d0ed7',
    authDomain: 'ccms-d0ed7.firebaseapp.com',
    storageBucket: 'ccms-d0ed7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASv-Q4zXgElsTq8-bLIenB_KvNigXV15I',
    appId: '1:1392979323:android:f6e3ffe53cbab02d4461de',
    messagingSenderId: '1392979323',
    projectId: 'ccms-d0ed7',
    storageBucket: 'ccms-d0ed7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMw0P8HA8FRZxjKZncgXwsHvmkozJk0pM',
    appId: '1:1392979323:ios:a486dd95e8848c014461de',
    messagingSenderId: '1392979323',
    projectId: 'ccms-d0ed7',
    storageBucket: 'ccms-d0ed7.firebasestorage.app',
    iosBundleId: 'com.example.ccms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMw0P8HA8FRZxjKZncgXwsHvmkozJk0pM',
    appId: '1:1392979323:ios:a486dd95e8848c014461de',
    messagingSenderId: '1392979323',
    projectId: 'ccms-d0ed7',
    storageBucket: 'ccms-d0ed7.firebasestorage.app',
    iosBundleId: 'com.example.ccms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD87lsqTNGwvcecyoitYoBJ6QZCKoyCRQ',
    appId: '1:1392979323:web:e2c4bfa8323c35c94461de',
    messagingSenderId: '1392979323',
    projectId: 'ccms-d0ed7',
    authDomain: 'ccms-d0ed7.firebaseapp.com',
    storageBucket: 'ccms-d0ed7.firebasestorage.app',
  );
}
